### ISSUE TITLE
tslint 를 eslint 로 대체하는 것을 어떨까요?

### ISSUE THREAD

**Issue by jjangga0214** [tonyfromundefined/codelab-graphql#5]
현업에서 이미 tslint 를 문제없이 사용중인 여러 회사와 프로젝트가 있으니, 
그러한 경우는 eslint 로 당장 바꿀 필요는 없다고 생각합니다.

그러나 이 repo는 교육적 목적을 띄고 있는 만큼, 
deprecated 된 tslint 대신에 eslint 의 사용을 고려해보는 것은 어떨까요?

**Comment by tonyfromundefined** [comment]
저도 그래서 ㅎㅎ ESLint로 설정하려고 https://github.com/typescript-eslint/tslint-to-eslint-config 를 처음 사용해봤는데요. 아직 ESLint에서 TSLint의 기능을 Fully Support하지 않는다고해서 TSLint로 일단 두었습니다.

그리고 저 CLI를 사용하면 ESLint 설정이 엄청나게 복잡해지더라구요.
